### ISSUE TITLE
Replace web3js to help reduce package size

### ISSUE THREAD

**Issue by mikemcdonald** [paraswap/paraswap-sdk#104]
Because Paraswap uses web3 the package size is enormous see - https://bundlephobia.com/package/paraswap@5.0.1

<img width="1327" alt="Screen Shot 2022-02-07 at 12 30 14 AM" src="https://user-images.githubusercontent.com/5049108/152740422-d281b78d-da21-4817-bdb5-c634a32617d4.png">

I attached a screenshot of the Balancer frontend bundle, almost a quarter (circled in red) comes from this sdk. Are there any plans to move to ethers?

**Comment by mounibec** [comment]
Thanks @mikemcdonald, we'll check this asap

**Comment by mwamedacen** [comment]
Hello @mikemcdonald, we **prereleased** our new bundle-optimised SDK
- @paraswap/sdk@5.6.0-alpha.2
- Readme: https://github.com/paraswap/paraswap-sdk/blob/sdk-refactoring/README.md
- Changes: https://github.com/paraswap/paraswap-sdk/pull/113
We would love to have your feedback 😉

**Comment by mikemcdonald** [comment]
Massive difference. Thanks for looking into this
