### ISSUE TITLE
Can we "import" tokens?

### ISSUE THREAD

**Issue by astanciu** [paraswap/paraswap-sdk#97]
Maybe I'm doing something wrong but it appears like this SDK only allows swapping of the built in tokens, or the tokens available via getTokens(). Is this true?

I'm getting a 400 / Token not found error when I try to swap a valid token that exists on Avalanche network. In the paraswap.io UI we have the option of "importing" new tokens... Is there a way to do that with the SDK? seems odd to whitelist token addresses... but again, maybe I'm doing something wrong.

**Comment by tedircks** [comment]
Any updates on this @astanciu? I'm interested in similar functionality.

**Comment by ColonelJ** [comment]
You can trade any token, you simply need to pass the srcDecimals/destDecimals arguments!

Apologies that you didn't get an answer sooner...  You would have found the answer quite prominently written in our [API documentation](https://developers.paraswap.network/api/get-rate-for-a-token-pair) though.
